import { ArrowRight, BookOpen, FileSearch, FileText, MessageCircleQuestion } from 'lucide-react'
import { Link } from 'react-router-dom'

const steps = [{ title: '积累素材', text: '沉淀项目经历、金句和行业信息', to: '/materials' }, { title: '解析 JD', text: '拆解目标岗位的要求和关键词。', to: '/jd' }, { title: '生成简历', text: '基于真实素材组织有针对性的简历', to: '/resume' }, { title: '准备面试', text: '围绕岗位和简历准备高质量回答。', to: '/interview' }]
const features = [{ title: '素材库', text: '统一管理求职过程中积累的全部信息。', to: '/materials', icon: BookOpen }, { title: 'JD 解析', text: '快速看懂岗位要求，找到匹配短板。', to: '/jd', icon: FileSearch }, { title: '简历生成', text: '按目标岗位组织真实经历与项目成果。', to: '/resume', icon: FileText }, { title: '面试准备', text: '沉淀自我介绍、行为题与反问清单。', to: '/interview', icon: MessageCircleQuestion }]

export function HomePage() { return <div>
  <section className="relative flex min-h-[min(52vh,540px)] items-center overflow-hidden rounded-3xl bg-slate-900 px-7 py-10 text-white md:px-12"><div className="relative z-10 max-w-2xl"><h1 className="text-3xl font-semibold tracking-tight md:text-5xl">把真实的经历，变成更<span className="font-bold text-[1.05em] text-[#22D3EE]">有竞争力</span>的<br className="hidden sm:block" />求职表达</h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300 md:text-base">从建立素材库开始，梳理经历，匹配岗位，生成更贴合目标的简历与面试准备。</p><Link to="/materials" className="button-primary mt-10 bg-[#22D3EE] hover:bg-indigo-400">先去建立素材库 <ArrowRight size={16} /></Link></div><div className="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-indigo-600/30 blur-3xl" /></section>
  <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-indigo-600">使用路径</p><h2 className="mt-2 text-2xl font-semibold">四步完成一次求职准备</h2></div></div><div className="mt-5 grid gap-4 md:grid-cols-4">{steps.map((step, index) => <Link to={step.to} className="panel group px-5 py-3 transition hover:-translate-y-0.5 hover:border-indigo-300 active:translate-y-0" key={step.title}><span className="text-sm font-semibold text-indigo-500">0{index + 1}</span><h3 className="mt-6 font-semibold">{step.title}</h3><p className="mt-2 whitespace-nowrap text-xs leading-6 text-slate-500 dark:text-slate-400">{step.text}</p><ArrowRight size={16} className="mt-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-indigo-500" /></Link>)}</div></section>
  <section className="mt-6"><h2 className="text-2xl font-semibold">核心功能</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{features.map(({ title, text, to, icon: Icon }) => <Link to={to} key={title} className="panel group flex items-start gap-4 p-5 transition hover:-translate-y-0.5 hover:border-indigo-300"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950/60 dark:text-[#4CC9F0]"><Icon size={20} /></span><span><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{text}</p></span><ArrowRight className="ml-auto text-slate-300 transition group-hover:translate-x-1 group-hover:text-indigo-500" size={18} /></Link>)}</div></section>
  <p className="mt-8 rounded-xl border border-slate-200 bg-slate-100/80 px-4 py-3 text-center text-xs leading-5 text-slate-500 dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-400">所有数据均存储在浏览器本地，不上传任何服务器，保障个人经历隐私。</p>
 </div> }
