import { ChevronDown, Download, FileImage, FileText, FileType } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { exportMarkdown, exportPng, exportWord, printPreview } from '@/utils/exportDocument'

export function ExportMenu({ content, title, previewRef, onToast }: { content: string; title: string; previewRef: React.RefObject<HTMLDivElement>; onToast: (message: string) => void }) {
  const [open, setOpen] = useState(false)
  const [busy, setBusy] = useState(false)
  const rootRef = useRef<HTMLDivElement>(null)
  useEffect(() => { const close = (event: MouseEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  const run = async (action: () => void | Promise<void>) => { if (busy) return; if (!content.trim()) { setOpen(false); onToast('暂无内容可导出'); return } setOpen(false); setBusy(true); try { await action(); onToast('导出成功') } catch (error) { console.error('[Export] failed', error); onToast('导出失败，请重试') } finally { setBusy(false) } }
  return <div className="relative" ref={rootRef}><button type="button" disabled={busy} className="button-secondary py-2" onClick={() => setOpen((value) => !value)}><Download size={15} />{busy ? '导出中…' : '导出'}{!busy && <ChevronDown size={15} />}</button>{open && <div className="absolute right-0 z-20 mt-2 w-52 rounded-xl border bg-white p-1.5 shadow-xl dark:border-slate-700 dark:bg-slate-900"><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50 dark:hover:bg-slate-800" onClick={() => void run(() => exportMarkdown(content, title))}><FileText size={15} />Markdown 文档 (.md)</button><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50 dark:hover:bg-slate-800" onClick={() => void run(() => printPreview(title))}><FileType size={15} />PDF 文档 (.pdf)</button><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50 dark:hover:bg-slate-800" onClick={() => void run(() => previewRef.current ? exportWord(previewRef.current, title) : Promise.reject())}><FileText size={15} />Word 文档 (.docx)</button><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50 dark:hover:bg-slate-800" onClick={() => void run(() => previewRef.current ? exportPng(previewRef.current, title) : Promise.reject())}><FileImage size={15} />高清长图 (.png)</button></div>}</div>
}
